config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :welcome, only:[:index]
  root "welcome#index"
  resources :posts, only:[:index,:show,:create]
  resources :likes, only:[:create]
  resources :users, only:[:update,:index,:show]
  resources :relationships, only:[:create,:update]
  resources :rooms, only:[:create,:show]
  
  resources :events do
    member do
      patch 'replace'
    end
  end
  
  resources :events, only:[:index,:create,:show,:edit,:update,:replace]
  resources :rooms, only:[:show]
  
  resources :messages do
    collection do
      post 'make'
    end
  end
  resources :messages, only:[:create,:make]
  
  resources :event_members do
    collection do
      post 'change'
    end
  end
  
  resources :event_members, only:[:create,:change]
end

app/models/event.rb
class Event < ApplicationRecord
  default_scope -> {order(created_at: :desc)}
  belongs_to :user
  has_many :event_members
  mount_uploaders :files, FilesUploader
  
  validates :title, presence: true, length: {maximum: 20}
  validates :body, length: {maximum: 500}
  validates :files, presence: true
  validates :recruit_num, presence: true, numericality: {only_integer: true,greater_than: 0}
  validates :place, presence: true, length: {maximum: 100}
  validates :event_date, presence: true
  validates :deadline, presence: true
  validates :user_id, presence: true
  
  def self.search(search)
    if search
      Event.joins(:user).where(['users.name LIKE ?',"%#{search["user_name"]}%"]).where(['title LIKE ?',"%#{search["title"]}%"]).where(['place LIKE ?',"%#{search["place"]}%"])
    else
      Event.all
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, :only => [:index,:create,:edit,:show,:update,:replace]
  before_action :correct_referrer
  
  def index
    @event = Event.new
    @events = Event.search(params[:search]).paginate(page: params[:page], per_page: 10)
  end
  
  def create
    
    @event = Event.new(event_params)
    
    if @event.save
      flash[:notice] = "イベントを作成しました"
    else
      flash[:alert] = "イベント作成に失敗しました"
    end
    
    redirect_to events_url
    
  end
  
  def show
    @event = Event.find(params[:id])
    @event_member = EventMember.new
    @pre_users = User.joins(:event_members).where('event_members.event_id=? AND event_members.status=?',@event.id,0)
    @users = User.joins(:event_members).where('event_members.event_id=? AND event_members.status=?',@event.id,1)
    @relationship = Relationship.new
    @message = Message.new
    @room = enterRoom(@event.user_id,current_user.id)
  end
  
  def edit
    @event = Event.find(params[:id])
    @user = current_user
    @pre_users = User.joins(:event_members).where('event_members.event_id=? AND event_members.status=?',@event.id,0)
    @users = User.joins(:event_members).where('event_members.event_id=? AND event_members.status=?',@event.id,1)
    @relationship = Relationship.new
    @message = Message.new
    @room = enterRoom(@event.user_id,current_user.id)
  end
  
  def update
    
    if Event.find(params[:id]).update(event_params)
      flash[:notice] = "イベント情報を更新しました"
      redirect_to event_url(params[:id])
    else
      flash[:alert] = "更新に失敗しました"
      redirect_to edit_event_url(params[:id])
    end
  end
  
  def replace
    @event = Event.find(params[:id])
    # 選択されたファイルを削除
    remove_file_at_index(params[:file_id].to_i)
    
    unless @event.save
      flash[:alert] = '変更に失敗しました' 
      redirect_back(fallback_location: root_path)
    end
    
    # ファイルの追加
    add_file(params[:event][:files],params[:file_id].to_i)
    
    unless @event.save
      flash[:alert] = '変更に失敗しました' 
      redirect_back(fallback_location: root_path)
    end
    
    flash[:notice] = '画像を変更しました'
    redirect_back(fallback_location: root_path)
  end
  
  private
    
    def event_params
      params.require(:event).permit(:title,{files:[]},:body,:place,:recruit_num,:event_date,:deadline).merge( user_id: current_user.id )
    end
    
    def correct_referrer
      if request.referer.nil?
        flash[:alert] = "無効なアクセス"
        redirect_to root_url
      end
    end
    
    def add_file(new_files,index)
      files = @event.files
      files.insert(index,new_files) 
      @event.files = files
    end

    def remove_file_at_index(index)
      remain_files = @event.files # copy the array
      deleted_file = remain_files.delete_at(index) # delete the target file
      deleted_file.try(:remove!) # delete file from S3
      @event.files = remain_files # assign back
    end
      
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_user_list_for_edit.html.erb
<% users.each do |user| %>
  <div class="friend">
    <%= render 'share/user_profile', user: user %>
    <%= check_box_tag 'user_id[]', user.id, nil, {} %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="container">
  <!--event-edit-form-->
  <%= form_for @event do |f| %>
    <h1><%= f.text_field :title, class: "text-center form-control" %></h1>
  <div class="row">
    <!--企画者情報-->
    <div class="col-md-3">
      <h3 class= "text-center">企画者</h3>
      <%= render "share/userInfo", user: @event.user, relationship: @relationship, room: @room %>
    </div>
    
    <!--イベント情報-->
    <div class="col-md-9">
      <div class="article-wrap">
        <ul class="article-files">
          <% file_id = 0 %>
          <% @event.files.each do |file| %>
            <li>
              <% if isPicture?(file.url) %>
                <a href='#' data-toggle="modal" data-target="#replaceFileModal" data-event-id="<%= @event.id %>" data-file-id="<%= file_id %> ">
                  <%= image_tag file.url %>
                </a>
              <% elsif isVideo?(file.url)%>
                <a href='#' data-toggle="modal" data-target="#replaceFileModal" data-event-id="<%= @event.id %>" data-file-id="<%= file_id %>">
                  <%= video_tag file.url, controls: true %>
                </a>
              <% end %>
              <% file_id += 1 %>
            </li>
          <% end %>
        </ul>
        <h4>企画の詳細</h4>
        <p><%= f.text_area :body, class: "form-control" %></p>
        <p><i class="fas fa-map-marked-alt"></i> 場所 <%= f.text_field :place, class: "form-control" %></p>
        <p><i class="fas fa-calendar-alt"></i> 開催日 <%= f.date_field :event_date, class: "form-control" %></p>
        <p><i class="fas fa-calendar-alt"></i> 締切 <%= f.date_field :deadline, class: "form-control" %></p>
        <p><i class="fas fa-user-circle"></i> 人数 <%= f.number_field :recruit_num, class: "form-control" %></p>
      </div>
    </div>
  </div>
  
  <%= f.submit "変更を保存する", class: "btn btn-primary" %>
  <% end %>
  <!--event-edit-formの終わり-->
  
  <%= form_tag change_event_members_path, method: 'post' do %>
  <!--参加者情報-->
  <h4>参加者</h4>
  <%= render 'user_list_for_edit', users: @users %>
  <h4>参加希望者</h4>
  <%= render 'user_list_for_edit', users: @pre_users %>
  
  <%= hidden_field_tag :event_id, @event.id %>
  <%= submit_tag "参加不参加を変更する",class: "btn btn-primary" %>
  <br>
  <% end %>
  <!--change-formのおわり-->
</div>

<script>
  $('#replaceFileModal').on('show.bs.modal', function (event) {
    var anchor = $(event.relatedTarget)
    var file_id = anchor.data('file-id')
    
    var input = document.getElementById('event_file_id')
    input.value = file_id
  });
</script>

<!--modal-->
<!--modal to edit user-->
<%= render 'share/editUserModal', user: current_user %>
<%= render 'share/replaceFileModal', event: @event %>

app/views/events/index.html.erb
<div class="container">
  <h1 class="text-center">Events</h1>
  
  <div class="search-win">
    <%= form_tag events_path, method: 'get' do %>
      <%= text_field :search, :user_name ,class: 'form-control',placeholder: "ユーザ名"%>
      <br>
      <%= text_field :search, :title,class: 'form-control', placeholder: "イベント名" %>
      <br>
      <%= text_field :search, :place,class: 'form-control', placeholder: "開催地" %>
      <br>
      <%= submit_tag "検索する", class:"btn btn-primary" %>
    <% end %>
  </div>
  
  <!--event list-->
  <%= render 'share/event', events: @events %>
  <%= will_paginate @events %>
</div>

<!--modal trigger-->
<button type="button" class="btn btn-post" data-toggle="modal" data-target="#newEventModal">
  <i class="fas fa-pen"></i>
</button>

<!--modal-->
<div class="modal fade" id="newEventModal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="newEventModalLabel">イベントを作成する</h4>
        <button type="button" class="close" data-dismiss="modal">
          <span>&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_for @event do |f| %>
          <h5>タイトル</h5>
          <%= f.text_field :title, class: "form-control", placeholder: "タイトル" %>
          <h5>画像・動画</h5>
          <%= f.file_field :files, multiple: true, accept:'image/jpg,image/jpeg,image/gif,video/mp4,video/mov,video/wmv' %>
          <h5>詳細</h5>
          <%= f.text_area :body, class: "form-control", placeholder: "詳細を入力してください" %>
          <h5>場所</h5>
          <%= f.text_field :place, class: "form-control", placeholder: "住所を入力してください" %>
          <h5>人数</h5>
          <%= f.number_field :recruit_num %>
          <h5>開催日</h5>
          <%= f.date_field :event_date %>
          <h5>募集締め切り</h5>
          <%= f.date_field :deadline %>
          <p></p>
          <%= f.submit "企画を作成する", class: "btn btn-primary" %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="container">
  <% if current_user.id == @event.user_id %>
    <%= link_to "編集する", edit_event_path(@event), class: "event-header btn btn-primary" %>
  <% else %>
    <% if EventMember.where(user_id: current_user.id ,event_id: @event.id).exists? %>
      <span class="event-header btn btn-secondary">参加済み</span>
    <% else %>
      <%= form_for @event_member do |f| %>
        <%= f.hidden_field :event_id, value: @event.id %>
        <%= f.submit "参加する", class: "event-header btn btn-primary" %>
      <% end %>
    <% end %>
  <% end %>
  
  <h1 class="text-center"><%= @event.title %></h1>
  <div class="row">
    <!--企画者情報-->
    <div class="col-md-3">
      <h3 class= "text-center">企画者</h3>
      <%= render "share/userInfo", user: @event.user, relationship: @relationship, room: @room %>
    </div>
  
    <!--イベント情報-->
    <div class="col-md-9">
      <div class="article-wrap">
        <ul class="article-files">
          <% @event.files.each do |file| %>
            <li>
              <% if isPicture?(file.url) %>
                <%= image_tag file.url %>
              <% elsif isVideo?(file.url)%>
                <%= video_tag file.url, controls: true %>
              <% end %>
            </li>
          <% end %>
        </ul>
        <h4>企画の詳細</h4>
        <p><%= @event.body %></p>
        <p><i class="fas fa-map-marked-alt"></i> <%= @event.place %></p>
        <p><i class="fas fa-calendar-alt"></i> <%= @event.event_date.strftime("%Y年%m月%d日") %></p>
        <p><i class="fas fa-user-circle"></i> <%= @event.recruit_num %>人</p>
      </div>
    </div>
  </div>
  
  <!--参加者情報-->
  <h4>参加者</h4>
  <%= render 'share/user_list', users: @users, relationship: @relationship %>
  <h4>参加希望者</h4>
  <%= render 'share/user_list', users: @pre_users, relationship: @relationship %>
  
</div>

<script>
  $('#startChatModal').on('show.bs.modal', function (event) {
    var button = $(event.relatedTarget);
    var user_id = button.data('user-id');
    var input = document.createElement('input');
    input.type = 'hidden';
    input.name = 'user_id';
    input.value = user_id;
    input.id = 'start-chat'
    var parent = document.getElementById('new_message');
    parent.appendChild(input);
  });
  
  $('#close-modal').click(function(){
    var input = document.getElementById('start-chat');
    input.remove();
  })
</script>

<!--modal-->
<!--modal for edit user-->
<%= render 'share/editUserModal', user: current_user %>

<!--modal to start chat -->
<%= render 'share/startChatModal',message: @message %>