config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :welcome, only:[:index]
  root "welcome#index"
  resources :posts, only:[:index,:show,:create]
  resources :likes, only:[:create]
  resources :users, only:[:update,:index,:show]
  resources :relationships, only:[:create,:update]
  resources :rooms, only:[:create,:show]
  
  resources :events do
    member do
      patch 'replace'
    end
  end
  
  resources :events, only:[:index,:create,:show,:edit,:update,:replace]
  resources :rooms, only:[:show]
  
  resources :messages do
    collection do
      post 'make'
    end
  end
  resources :messages, only:[:create,:make]
  
  resources :event_members do
    collection do
      post 'change'
    end
  end
  
  resources :event_members, only:[:create,:change]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true, :uniqueness => {:scope => :room_id}
  validates :room_id, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
  default_scope -> {order(created_at: :desc)}
  belongs_to :user
  has_many :event_members
  mount_uploaders :files, FilesUploader
  
  validates :title, presence: true, length: {maximum: 20}
  validates :body, length: {maximum: 500}
  validates :files, presence: true
  validates :recruit_num, presence: true, numericality: {only_integer: true,greater_than: 0}
  validates :place, presence: true, length: {maximum: 100}
  validates :event_date, presence: true
  validates :deadline, presence: true
  validates :user_id, presence: true
  
  def self.search(search)
    if search
      Event.joins(:user).where(['users.name LIKE ?',"%#{search["user_name"]}%"]).where(['title LIKE ?',"%#{search["title"]}%"]).where(['place LIKE ?',"%#{search["place"]}%"])
    else
      Event.all
    end
  end
end

app/models/event_member.rb
class EventMember < ApplicationRecord
  belongs_to :event
  belongs_to :user
  
  validates :event_id, presence: true, :uniqueness => {:scope => :user_id}
  validates :user_id, presence: true
  validates :status, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  
  validates :user_id, presence: true, :uniqueness => {:scope => :post_id}
  validates :post_id, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  
  validates :body, presence: true
  validates :user_id, presence: true
  validates :room_id, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :like, dependent: :destroy
  mount_uploaders :files, FilesUploader
  
  validates :user_id, presence: true
  validates :body, length: {maximum: 140}
  validates :files, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  has_many :users
  
  validates :user_id, presence: true, :uniqueness => {:scope => :friend_id}
  validates :friend_id, presence: true
  validates :status, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entries
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable
  has_many :posts, dependent: :destroy
  has_many :relationships, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :event_members, dependent: :destroy
  mount_uploader :image, ImageUploader
  
  validates :name, length: {maximum: 30}
  validates :intro, length: {maximum: 140}
  
  def self.search(search)
    if search
      User.where(['name LIKE ?', "%#{search}%"])
    else
      User.all
    end
  end
  
  def self.find_for_oauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.first_name
      
      image_url=auth.info.image.to_s + "?type=large"
      user.remote_image_url = image_url.gsub("http","https")
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!, :only => [:create]
  before_action :correct_referrer
  
  def create
    @like = Like.new(user_id: current_user.id,post_id: params[:post_id])
    
    if @like.save
      flash[:notice] = "いいねしました"
    else
      flash[:alert] = "いいねに失敗しました"
    end
    
    redirect_back(fallback_location: root_path)
    
  end 
  
  private
  
    def correct_referrer
      if request.referer.nil?
        flash[:alert] = "無効なアクセス"
        redirect_to root_url
      end
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, :only => [:index,:show,:create]
  before_action :correct_referrer
  
  def index
    # 友達のみ
    @friend_posts = Post.joins('INNER JOIN relationships on posts.user_id = relationships.user_id OR posts.user_id = relationships.friend_id').where('relationships.status = ? AND posts.user_id != ? AND (relationships.user_id=? OR relationships.friend_id=?)', 1, current_user.id,current_user.id,current_user.id).order('created_at desc').paginate(page: params[:page], per_page: 10)
    # 降順
    @new_posts = Post.order("created_at desc").paginate(page: params[:page], per_page: 10)
    # いいねがない場合表示されない
    @hot_posts = Post.joins(:like).group(:id).order("count(posts.id) desc").paginate(page: params[:page], per_page: 10)
    @post = Post.new
    
    if params[:tab].eql? 'friend'
      @friend_list = 'active'
      @friend_tab = 'active in'
    elsif params[:tab].eql? 'new'
      @new_list = 'active'
      @new_tab = 'active in'
    elsif params[:tab].eql? 'hot'
      @hot_list = 'active'
      @hot_tab = 'active in'
    else
      @friend_list = 'active'
      @friend_tab = 'active in'
    end
    
  end
  
  def show
    @post = Post.find(params[:id])
    @likes = Like.where(post_id: @post.id)
    @like = Like.new
    @user = current_user
    @relationship = Relationship.new
    @message = Message.new
    
    room_id = searchRoomId(@post.user_id,current_user.id)
    if room_id == 0
      @room = Room.new
    else
      @room = Room.find(room_id)
    end
    
  end
  
  def create
    @post = current_user.posts.build(post_params)
    
    if @post.save
      flash[:notice] = "投稿に成功しました"
    else
      flash[:alert] = "投稿に失敗しました"
    end
    
    redirect_to posts_url
  end
  
  private
    
    def post_params
      params.require(:post).permit(:body,{files:[]})
    end

    def correct_referrer
      if request.referer.nil?
        flash[:alert] = "無効なアクセス"
        redirect_to root_url
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def isPicture?(file)
    pictureExt = %w(.jpg .jpeg .gif .png)
    ext=File.extname(file).downcase
    return pictureExt.include?(ext)
  end
  
  def isVideo?(file)
    videoExt=%(.mp4 .mov .wmv)
    ext=File.extname(file).downcase
    return videoExt.include?(ext)
  end
  
  def isFriend?(id_a,id_b)
    
    if id_a == id_b
      return false
    end
    
    r1 = Relationship.find_by(user_id: id_a,friend_id: id_b)
    r2 = Relationship.find_by(user_id: id_b,friend_id: id_a)
    
    if  r1.present? 
      return r1.status
    elsif r2.present?
      return r2.status
    else
      return false
    end
  end
  
  def searchRoomId(id_a,id_b)
    
    if id_a == id_b
      return 0
    else
      entries = Entry.where(user_id: id_a)

      entries.each do |e|
        if Entry.where(user_id: id_b,room_id: e.room_id).exists?
          return e.room_id
        end
      end
      
      return 0
      
    end
  end
  
  def enterRoom(id_a,id_b)
    room_id = searchRoomId(id_a,id_b)
    
    if room_id == 0
      room = Room.new
    else
      room = Room.find(room_id)
    end
    
    return room
  end
  
  def userImage(user)
    if user.image?
      user.image.url(:thumb)
    else
      'user.jpg'
    end
  end 
  
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Campers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta  name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <%= favicon_link_tag('favicon.ico') %>
  </head>

  <body>
    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
          </button>
        <a href="/" class="navbar-brand"><i class="fas fa-campground"></i> Campers</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to "Events", events_path %></li>
              <li><%= link_to "Posts",posts_path %></li>
              <li><%= link_to "Users",users_path %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <%= image_tag userImage(current_user) %><%= "#{current_user.name}さん"%><span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <li class="dropdown-header">Menu</li>
                  <li><%= link_to 'My Page', root_path %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
              <li><%= link_to "Log in", new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    
    <div class="main-page">
      <div class="container">
        <% if notice %>
          <br>
          <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
          <br>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>
      </div>
      
      <%= yield %>
      
    </div>
    
  </body>
</html>

app/views/share/_editUserModal.html.erb
<!--modal to edit user-->
<div class="modal fade" id="editUserModal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="editUserModalLabel">ユーザー情報を編集する</h4>
        <button type="button" class="close" data-dismiss="modal">
          <span>&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_for user, :url => {controller: 'users', action: 'update',id: user.id} do |f| %>
          <%= f.file_field :image, accept:'image/jpg,image/jpeg,image/gif' %>
          <br>
          <%= f.text_field :name, class: "form-control",placeholder: "名前" %>
          <br>
          <%= f.text_area :intro, class: "form-control",placeholder:"自己紹介" %>
          <br>
          <%= f.submit "変更を保存する", class: "btn btn-primary" %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/share/_event.html.erb
<ul class = event-list>
  <% events.each do |event| %>
    <li>
      <div class="event-photo">
        <% if isPicture?(event.files.first.url) %>
          <%= link_to image_tag(event.files.first.url(:medium)), event_path(event) %>
        <% elsif isVideo?(event.files.first.url) %>
          <%= link_to video_tag(event.files.first.url,autoplay: true, loop: true, width: "200px"), event_path(event) %>
        <% end %>
      </div>
      <div class="event-owner text-left">
        <% if event.user.image? %>
          <%= image_tag(event.user.image.url(:thumb)) %>
        <% else %>
          <%= image_tag("user.jpg") %>
        <% end %>
        <%= event.user.name %>
      </div>
      <h4 class="text-left"><%= event.title %></h4>
      <div class="text-left">
        <p><i class="fas fa-map-marked-alt"></i> <%= event.place %></p>
        <p><i class="fas fa-calendar-alt"></i> <%= event.event_date.strftime("%Y年%m月%d日") %></p>
        <p><i class="fas fa-user-circle"></i> <%= event.recruit_num %>人</p>
      </div>
    </li>
  <% end %>
</ul>

app/views/share/_post.html.erb
<ul class ="post-list" >
  <% posts.each do |post| %>
    <li>
      <% if post.files? %>
        <% if isPicture?(post.files.first.url) %>
          <%= link_to image_tag(post.files.first.url(:medium)), post_path(post) %>
        <% elsif isVideo?(post.files.first.url) %>
          <%= link_to video_tag(post.files.first.url,autoplay: true,loop: true,width: "200px"), post_path(post) %>
        <% end %>
      <% end %>
      <div class="like-icon">
        <i class="fas fa-heart"> <%= Like.where(post_id: post.id).count %></i>
      </div>
    </li>
  <% end %>
</ul>

app/views/share/_replaceFileModal.html.erb
<!--modal to edit user-->
<div class="modal fade" id="replaceFileModal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="replaceFileModalLabel">写真を入れ替える</h4>
      </div>
      <div class="modal-body">
        <%= form_for(event, :url =>{ controller: 'events', action: 'replace' }, multipart: true) do |f| %>
          <%= f.file_field :files, accept:'image/jpg,image/jpeg,image/gif,video/mp4,video/mov,video/wmv' %>
          <br>
          <%= f.submit '変更する', class: 'btn btn-primary' %>
          <input type='hidden' name='file_id' value=nil id='event_file_id' >
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" id='close-modal' class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/share/_startChatModal.html.erb
<!--modal to start chat -->
<div class="modal fade" id="startChatModal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="startChatModalLabel">チャットを始める</h4>
      </div>
      <div class="modal-body">
        <%= form_for message, :url => {controller:"messages",action: "make" } do |f| %>
          <%= f.text_field :body, class: "form-control",placeholder: "ここに入力してください" %>
          
          <br>
          <%= f.submit "送信する", class: "btn btn-primary" %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" id="close-modal" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/share/_userInfo.html.erb
<!--user info-->
<div class="user-wrap">
  <div class="user-img">
    <% if user.image? %>
      <%= image_tag(user.image.url) %>
    <% else %>
      <%= image_tag("user.jpg") %>
    <% end %>
  </div>
  <div class="user-info">
    <h5><strong><%= user.name %></strong></h5>
    <p><small><%= user.intro %></small></p>
  </div>
</div>
<div class="btn-wrap">
<br>
<%= request.remote_ip %>
 <%= render 'share/user_btn', user: user, relationship: relationship %>
</div>

app/views/share/_user_btn.html.erb
<% if current_user.id == user.id %>
  <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#editUserModal" >
    編集する
  </button>
<% else %>
  <% if isFriend?(current_user.id,user.id)==1 %>
    <% room = enterRoom(current_user.id,user.id) %>
    <% if room.id.nil? %>
      <button type="button" class="btn btn-info" data-toggle="modal" data-target="#startChatModal" data-user-id="<%=user.id %>" >
        チャットを始める
      </button>
    <% else %>
      <%= link_to 'チャットする', room_path(room), class: 'btn btn-info' %>
    <% end %>
  <% elsif isFriend?(current_user.id,user.id)==0 %>
    <span class="btn btn-secondary">承認待ち</span>
  <% else %>
    <%= form_for relationship, :url => {controller: 'relationships',action: 'create', friend_id: user.id } do |f| %>
     <%= f.submit "友達申請", class: "btn btn-success" %>
    <% end %>
  <% end %>
<% end %>

app/views/share/_user_list.html.erb
<% users.each do |user| %>
  <div class="friend">
    <%= render 'share/user_profile', user: user %>
    <%= render 'share/user_btn',user: user, relationship: relationship %>
  </div>
  <hr>
<% end %>

app/views/share/_user_profile.html.erb
<div class="user-image">
  <%= image_tag(userImage(user)) %>
</div>
<div class="profile">
  <strong><%= link_to "#{user.name}", user_path(user) %></strong>
  <br>
  <small><%= user.intro %></small>
</div>